//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvantageTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvantageTool.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an LTI Advantage demonstration tool using .NET Core..
        /// </summary>
        public static string AboutLTITool {
            get {
                return ResourceManager.GetString("AboutLTITool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token URL.
        /// </summary>
        public static string AccessTokenUrl {
            get {
                return ResourceManager.GetString("AccessTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool can request an access token using this endpoint (for example to use the Names and Role Service)..
        /// </summary>
        public static string AccessTokenUrlDescription {
            get {
                return ResourceManager.GetString("AccessTokenUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization URL.
        /// </summary>
        public static string AuthorizationUrl {
            get {
                return ResourceManager.GetString("AuthorizationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool requests the identity token from this endpoint..
        /// </summary>
        public static string AuthorizationUrlDescription {
            get {
                return ResourceManager.GetString("AuthorizationUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your Platform to launch this Tool....
        /// </summary>
        public static string ConfigurePlatformToLaunch {
            get {
                return ResourceManager.GetString("ConfigurePlatformToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Linking Launch URL.
        /// </summary>
        public static string DeepLinkingLaunchUrl {
            get {
                return ResourceManager.GetString("DeepLinkingLaunchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to launch the tool&apos;s deep linking experience..
        /// </summary>
        public static string DeepLinkingLaunchUrlDescription {
            get {
                return ResourceManager.GetString("DeepLinkingLaunchUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for development keys see.
        /// </summary>
        public static string ForDevelopmentKeysSee {
            get {
                return ResourceManager.GetString("ForDevelopmentKeysSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Issuer for all messages that originate from the Platform..
        /// </summary>
        public static string IssuerDescription {
            get {
                return ResourceManager.GetString("IssuerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWK Set URL.
        /// </summary>
        public static string JwkSetUrl {
            get {
                return ResourceManager.GetString("JwkSetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool can retrieve the platform&apos;s public keys using this endpoint..
        /// </summary>
        public static string JwkSetUrlDescription {
            get {
                return ResourceManager.GetString("JwkSetUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch URL.
        /// </summary>
        public static string LaunchUrl {
            get {
                return ResourceManager.GetString("LaunchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to launch the tool&apos;s resource link experience..
        /// </summary>
        public static string LaunchUrlDescription {
            get {
                return ResourceManager.GetString("LaunchUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login URL.
        /// </summary>
        public static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to initiate the tool&apos;s OpenID Connect third party login..
        /// </summary>
        public static string LoginUrlDescription {
            get {
                return ResourceManager.GetString("LoginUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No platforms have been registered..
        /// </summary>
        public static string NoPlatformsRegistered {
            get {
                return ResourceManager.GetString("NoPlatformsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Platform.
        /// </summary>
        public static string PlatformDelete {
            get {
                return ResourceManager.GetString("PlatformDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Details.
        /// </summary>
        public static string PlatformDetails {
            get {
                return ResourceManager.GetString("PlatformDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Platform.
        /// </summary>
        public static string PlatformRegister {
            get {
                return ResourceManager.GetString("PlatformRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Settings.
        /// </summary>
        public static string PlatformSettings {
            get {
                return ResourceManager.GetString("PlatformSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the private key the tool will use to sign client credentials..
        /// </summary>
        public static string PrivateKeyDescription {
            get {
                return ResourceManager.GetString("PrivateKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the private key in PEM format..
        /// </summary>
        public static string PrivateKeyInPEMFormat {
            get {
                return ResourceManager.GetString("PrivateKeyInPEMFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is based on.
        /// </summary>
        public static string ProjectBasedOn {
            get {
                return ResourceManager.GetString("ProjectBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Platforms.
        /// </summary>
        public static string RegisteredPlatforms {
            get {
                return ResourceManager.GetString("RegisteredPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Platform.
        /// </summary>
        public static string RegisterNewPlatform {
            get {
                return ResourceManager.GetString("RegisterNewPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your Platform.
        /// </summary>
        public static string RegisterYourPlatform {
            get {
                return ResourceManager.GetString("RegisterYourPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to configure test Tools..
        /// </summary>
        public static string ToConfigure {
            get {
                return ResourceManager.GetString("ToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ToLogin {
            get {
                return ResourceManager.GetString("ToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Settings.
        /// </summary>
        public static string ToolSettings {
            get {
                return ResourceManager.GetString("ToolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool currently supports:.
        /// </summary>
        public static string ToolSupports {
            get {
                return ResourceManager.GetString("ToolSupports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to record the platform&apos;s OpenID Connect endpoints, and the client credentials you want this tool to use..
        /// </summary>
        public static string ToRecordOpenIdEndpointsAndCredentials {
            get {
                return ResourceManager.GetString("ToRecordOpenIdEndpointsAndCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this Tool with your Platform.
        /// </summary>
        public static string UseThisToolWithPlatform {
            get {
                return ResourceManager.GetString("UseThisToolWithPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..using this OpenID Connect Login Initiation Page.
        /// </summary>
        public static string UsingOpenIdConnect {
            get {
                return ResourceManager.GetString("UsingOpenIdConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Stranger!.
        /// </summary>
        public static string WelcomeStranger {
            get {
                return ResourceManager.GetString("WelcomeStranger", resourceCulture);
            }
        }
    }
}
